### ISSUE TITLE
Add a new config option to remove empty lines after flow control attributes.

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#157]
```erlang
-ifdef(TEST).
-include_lib("eunit/include/eunit.hrl").
-endif.
```
gets formatted to
```erlang
-ifdef(TEST).

-include_lib("eunit/include/eunit.hrl").

-endif.
```

Are those blank lines expected?

**My preference**: no blank lines.

**Comment by elbrujohalcon** [comment]
Yes, `default_formatter` groups attributes by name since #30. That's not likely to change anytime soon.

**Comment by paulo-ferraz-oliveira** [comment]
Hm... I'm not saying it should be made "generic" but considering it for [flow control as a special case](https://erlang.org/doc/reference_manual/macros.html#flow-control-in-macros).

**Comment by paulo-ferraz-oliveira** [comment]
> Yes, `default_formatter` groups attributes by name since #30. That's not likely to change anytime soon.

Are attributes possible to target by name? I'm asking because this is not something like declaring an `export`, a `type`, or an `export_type`, or even an `elvis` directive. This is flow control; oh, well, if there's no change, then there's no change - I tried 😢.

**Comment by elbrujohalcon** [comment]
Alright, if you feel so strongly about it… I'll reopen the ticket with the following description:

> **Add a new config option to remove empty lines after [flow control](https://erlang.org/doc/reference_manual/macros.html#flow-control-in-macros) attributes.**

**Comment by paulo-ferraz-oliveira** [comment]
> Alright, if you feel so strongly about it… I'll reopen the ticket with the following description:
> 
> > **Add a new config option to remove empty lines after [flow control](https://erlang.org/doc/reference_manual/macros.html#flow-control-in-macros) attributes.**

Thanks. In any case (though I do feel strong about it) I don't think I'm alone in this 👍.

(you can leave it with the lowest priority, no prob: `-spec(_).`s, for me, are the most important thing, at the moment 😄).

**Comment by elbrujohalcon** [comment]
Hummm… Turns out I can prevent the empty line _after_ `-ifdef.` (and after `-endif.` as well, FWIW), but I can't _always_ prevent the empty line _before_ `-endif.`. That's because each form in the list is separated from the next one by an empty line, except attributes with the same name.
So, I can get the default formatter to format your example exactly as you want it, @paulo-ferraz-oliveira (by cheating a bit, since what you have are 3 attributes), but it won't work for…

```erlang
-ifdef(SOME_MACRO).
f() -> x.
-endif.
```

This one (since what's in between is a function) will end up as…

```erlang
-ifdef(SOME_MACRO).
f() ->
    x.

-endif.
```

Which, I think, ends up being even worse than…

```erlang
-ifdef(SOME_MACRO).

f() ->
    x.

-endif.
```

So, since the code to format these things only _closer_ to what you want would be hacky at best, severely inconsistent at worst, I'm closing this ticket (again). Sorry.

PS: The changes would've also needed to apply not to all flow control attributes, but only to certain ones (e.g. it had to apply to `if`, `endif`, etc… but not `def` nor `undef`). That's also a bad sign.

**Comment by paulo-ferraz-oliveira** [comment]
> I'm closing this ticket (again). Sorry.

It's OK. I prefer consistency over hacks. Thanks for the consideration, though.
