### ISSUE TITLE
Formatting multiline lists

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#161]
```erlang
    Tags = [
        {<<"all">>, <<"work">>},
        {<<"and">>, <<"no-play">>},
        {<<"makes">>, <<"jack">>},
        {<<"a">>, <<"dull-boy">>}
    ],
```
gets formatted to
```erlang
    Tags =
        [{<<"all">>, <<"work">>},
         {<<"and">>, <<"no-play">>},
         {<<"makes">>, <<"jack">>},
         {<<"a">>, <<"dull-boy">>}],
```

I'd probably expect something like 
```erlang
    Tags = [{<<"all">>, <<"work">>},
            {<<"and">>, <<"no-play">>},
            {<<"makes">>, <<"jack">>},
            {<<"a">>, <<"dull-boy">>}],
```

**My preference**: what's on the first block.

**Comment by elbrujohalcon** [comment]
This is related to #162, #143, #159, #168, and others.
Basically, we're indenting match expressions after `=` since #75 because we found that not doing so led to very annoying all-to-the-right structures if the left side of `=` was large enough.
If #168 is fixed correctly, you might get what you expect. Not what you prefer, tho.
For your preference we'll need to get an agreement on https://github.com/AdRoll/rebar3_format/issues/159#issuecomment-698780044 which will likely end up requiring a new formatter module.
Anyway, since the work will be managed through the other issues. I'll close this one.

**Comment by paulo-ferraz-oliveira** [comment]
> If #168 is fixed correctly, you might get what you expect. Not what you prefer, tho.

Either way is OK, if there's no real choice 😄. I'll keep trying/using it until I feel comfortable with what it (`rebar3_format`) does.
