### ISSUE TITLE
Single-character variable assigment

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#168]
I have this
```erlang
    _ = ets:new(?SOCKETS_TABLE_NAME, [
        named_table,
        protected,
        {keypos, #socket_wrapper.id},
        {read_concurrency, true}
    ]),
```

It gets transformed to this
```erlang
    _ =
        ets:new(?SOCKETS_TABLE_NAME,
                [named_table, protected, {keypos, #socket_wrapper.id}, {read_concurrency, true}]),
```

**My preference**: don't touch the initial code.

An alternative?
```erlang
    _ = ets:new(?SOCKETS_TABLE_NAME,
                [named_table, protected, {keypos, #socket_wrapper.id}, {read_concurrency, true}]),
```
(since `_` is fairly common I imagine this is a common scenario).

**Comment by elbrujohalcon** [comment]
We discussed that with @ElFantasma in #143 and since this came around again now, I'm willing to take the heuristic approach of keeping things in the same line if what's left of the match expression is just a variable. It'll still cause the problems presented in #75 with `VeryLongVariableNames`. I'll see if I can still prevent that from happening by checking if the literal representation of the variable name is longer than `break_indent`…

**Comment by paulo-ferraz-oliveira** [comment]
😄 Thanks for considering it.

I was specifically referring to one-character-name variables (like `_` or `A`), not `VeryLongVariableNames`, since the former don't imply a huge change (and improve reading, for me at least), except for a line break.

In any case, since [I prefer my `=` to the left](https://github.com/AdRoll/rebar3_format/issues/151#issuecomment-698636301), that'll probably be handled elsewhere...

**Comment by elbrujohalcon** [comment]
This is not yet fixed. It still fails for `_`.
Ref: https://github.com/AdRoll/rebar3_format/pull/175#issuecomment-704867646
