### ISSUE TITLE
Use inline_attributes instead of inline_items in a `-spec` or `-callback`'s `when`

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [AdRoll/rebar3_format#190]
The `default_formatter` is formatting
```erlang
      when MetricName :: binary(),
           Value :: metric_value() | {unmanaged, float() | metric_value()},
           Type :: metric_type(),
           Tags :: [bin_kv()],
           Result :: ok.
```

as 
```erlang
     when MetricName :: binary(),
          Value :: metric_value() | {unmanaged, float() | metric_value()},
          Type :: metric_type(), Tags :: [bin_kv()], Result :: ok.
```

when option `inline_items` is `{when_over, 2}`.

**Expected behavior**
I'd expect not `inline_items`, but `inline_attributes`, to affect this. **Note**: I understand `when` is followed by a list, but `-spec` is an attribute, so...

In any case, whatever the decision, the README could also be improved to _state the obvious_ (?).

**Comment by elbrujohalcon** [comment]
This is definitively _not_ a bug. I'm turning it into a possible enhancement, for consideration…

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, sorry about that. It's **isn't** a bug.

**Comment by elbrujohalcon** [comment]
One important thing to notice is that the default value for `inline_attributes` is `all`. In other words, by using `inline_attributes` for this, we'll (by default) force the exact behavior you want to avoid in the first place.

**Comment by elbrujohalcon** [comment]
Actually, @paulo-ferraz-oliveira … can you check this scenario again?

In my computer, this code…
```erlang
-spec x(MetricName, Value, Type, Tags) -> Result       when MetricName :: binary(),
           Value :: metric_value() | {unmanaged, float() | metric_value()},
           Type :: metric_type(),
           Tags :: [bin_kv()],
           Result :: ok.

x(metric_name, value, type, tags) -> result.
```

…gets formatted this way…

```erlang
-spec x(MetricName, Value, Type, Tags) -> Result
     when MetricName :: binary(),
          Value :: metric_value() | {unmanaged, float() | metric_value()},
          Type :: metric_type(),
          Tags :: [bin_kv()],
          Result :: ok.
x(metric_name, value, type, tags) ->
    result.
```

That looks fine to me.

**Comment by elbrujohalcon** [comment]
Moreover, the actual issue here is that using `inline_attributes` for all attributes (and all lists within those attributes) which will be the natural conclusion of your _`-spec` is an attribute_ comment, would (by default) inline everything in every `spec`, `record`, `type`, etc…

It will turn this…

```erlang
-type child_spec() :: #{name := child_id(),
                        start := mfargs(),
                        restart => restart(),
                        shutdown => shutdown(),
                        type => worker(),
                        modules => modules()} |
                      {Id :: child_id(),
                       StartFunc :: mfargs(),
                       Restart :: restart(),
                       Shutdown :: shutdown(),
                       Type :: worker(),
                       Modules :: modules()}.
```

…into this…

```erlang
-type child_spec() :: #{name := child_id(), start := mfargs(), restart => restart(),
                        shutdown => shutdown(), type => worker(), modules => modules()} |
                      {Id :: child_id(), StartFunc :: mfargs(), Restart :: restart(),
                       Shutdown :: shutdown(), Type :: worker(), Modules :: modules()}.
```

…unless you specify a non-default value for `inline_attributes`.

I'm not entirely sure we want that. I still think that lists of things within attributes should still be laid out as lists (i.e. respecting `inline_items` and not `inline_attributes`).

On the other hand… _conjunctions_ (i.e. list of clauses joined by `,` - like the stuff that follows the `when` keyword), may benefit from a new `inline_conjunctions` setting. This setting will affect `when`s on specs and callbacks, but also guards in functions, case statements, and even `if` statements.

@juanbono @diegomanuel @facundoolano @ElFantasma what do you think?

**Comment by elbrujohalcon** [comment]
After talking with @paulo-ferraz-oliveira on Slack we came to the conclusion that implementing `inline_conjunctions => all | none | {when_over, pos_integer()}.` with `force_inlining` (which should be renamed `force_indentation`, BTW) and default `all` (like `inline_attributes`) is the right thing to do.

**Comment by paulo-ferraz-oliveira** [comment]
I like the fact that an option would be available to allow controlling conjunctions' format/placement.
