### ISSUE TITLE
Don't format numbers written with sintactic sugar 

### ISSUE THREAD

**Issue by juanbono** [AdRoll/rebar3_format#24]
In erlang there are different ways of writing the same number. In some cases one is more convenient than the others (specially when dealing with numbers in different bases and scientific notation)
Example:
```erlang
{
        1.00000000001,
        16#FFFFFFFF,
        2#101010101,
        8#11111,
        -1.0e+001,
        0.5e-1,
        12312.231234e12
    }
```
becomes:
```erlang
{1.0, 4294967295, 341, 4681, -1.0e+1, 5.0e-2, 1.2312231234e+16}
```

**Comment by juanbono** [comment]
Fixed by #35

**Comment by juanbono** [comment]
There is 1 case left: `16#FFFFFFFF` is being converted to `4294967295`

**Comment by facundoolano** [comment]
I see the formatter is turning `0.5` into `5.0e-1` which is not great

**Comment by szTheory** [comment]
I noticed it's also formatting `1_000` to `1000`.


**Note**

I wanted to add a test case to the rebar3_format source like in [this commit](https://github.com/AdRoll/rebar3_format/commit/b48c488700c64320852e46044cac3b9acfb49d68#diff-46355d2927d6aef99b1f49cc3d59ae82R13) but I get an error during `rebar3 test` even when running a clean copy of the master source without changes:

```
src/formatters/otp_formatter.erl
 530: Call to missing or unexported function erl_syntax:cond_expr_clauses/1
```

maybe because I'm on a different version of Erlang than the CI. I don't see `erl_syntax:cond_expr_clauses/1` in the Erlang docs or OTP source so maybe it's deprecated and they removed it? My version is :

```
➜ erl -version
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.0.2
```

and the CI is:

```
$ erl -version
Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3
```
