### ISSUE TITLE
Module attribute grouping

### ISSUE THREAD

**Issue by facundoolano** [AdRoll/rebar3_format#30]
Ideally I would like to be able to have:

```erl
-type count() :: non_neg_integer().
-type expiry() :: milliseconds().
-type penalty() :: number().

-type pos_number() :: number().
-type buffer() :: term().
-type packet() :: binary().
```

If that is not an option, I would prefer to have all `-type` lines together, rather than introducing a new line between each of them.

On the same note, I think it would be desirable to group the same directives together, and force a given order (e.g. module comes first, then types, then exports, etc.) so

```erl
-behavior(application).

-export([start/0, stop/0]).

-export([start/2, stop/1]).

-behavior(supervisor).
```

Becomes

```erl
-behavior(application).
-behavior(supervisor).

-export([start/0, stop/0]).
-export([start/2, stop/1]).
```

**Comment by elbrujohalcon** [comment]
Since #47, no empty lines are added between attributes, except for the last one in each group.
So if you group attributes on your source, they'll remain grouped in the formatted code.
How pressing is the need to auto-group attributes, @facundoolano?
It's not a trivial thing to implement and it has *tons* of corner cases. For instance: You won't like to group all `-spec`s together, some parse transforms will need attributes placed in _specific_ positions and you definitely can *not* place all `-if*…` or `-endif` attributes together 🤦‍♂

**Comment by facundoolano** [comment]
I don't think auto-group is important, considering what you already have implemented

**Comment by facundoolano** [comment]
Feel free to close this one.
