### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by Zalastax** [AdRoll/rebar3_format#37]
In https://github.com/erlang/otp/pull/2451, I asked whether this tool can be used without rebar3. @elbrujohalcon answered that it's possible but not supported. Would you be willing to support a CLI? I've done this before in https://github.com/josefs/Gradualizer/blob/master/src/gradualizer_cli.erl so implementing it should be fairly quick but I want to check with you before starting.

**Comment by juanbono** [comment]
That would be great! 
Thank you :)

**Comment by elbrujohalcon** [comment]
I'm closing this ticket since the complexity of adding (and more importantly _maintaining_) a command-line interface is far larger than the benefits that it will produce.

**Comment by paulo-ferraz-oliveira** [comment]
At the same time, I guess one can always install the plugin as global and, voilà, it's basically a CLI tool.

**Comment by elbrujohalcon** [comment]
Well… You still need to make sure all devs are using the same version of the standalone script, right? 

And you also need to make sure that all your apps are expected to be formatted with the same version (particularly for CI).

People didn't like it around here when I added the formatter plugin to our apps as `[rebar3_format]` (i.e. without specifying a version) and then went in and published a new release, thus deeming all their code in every open PR… _unformatted_. 🙈 

That's why we have stuff like this in our apps: https://github.com/AdRoll/spillway/blob/d6e5b11ccbb8192dab04b9c3b619be61e60114f3/rebar.config#L40-L44
