### ISSUE TITLE
Consider using themes/styles instead of multiple config options

### ISSUE THREAD

**Issue by elbrujohalcon** [AdRoll/rebar3_format#64]
Since we started this project, we considered `erl_prettypr` as the _canonical_ way of formatting Erlang code. We did have to implement our own `rebar3_prettypr` module since we wanted that to be more flexible/configurable and we also needed to fix some bugs there but we've been very strict with our decision to avoid changing the way the original one formats stuff (except for the mixture of tabs and spaces).

That way, if you format your code with just `rebar3 format` (i.e. without any additional option anywhere), you will get OTP-styled code (i.e. _canonically formatted_ code). It might not be your favorite way of formatting Erlang code, but it is _the default way_, _the OTP way_. And if you want to format the code in your favorite way, you can simply tweak the options here and there.

Now, after trying to apply the formatter to several projects, we're slowly realizing that `erl_prettypr` doesn't really format the code like the code in the OTP repo. It's close, but not even close enough and it has many quirks. It goes a long way, but we're not sure if anybody will ever want their projects formatted that way, let alone the OTP team. 😱 

We certainly don't and that's why we added several options, like `inline_expressions` or `inline_items`.
We could keep adding options to get the formatter to write the code in the way _we_ like it, but each option that we add duplicates (or even more than that sometimes) the number of different ways of formatting the code, which is undesirable in the long run (particularly for small things like #61, #59 and others).

Besides, implementing stuff like #36 (which is something I would personally love to see) becomes harder and harder with each option that we add.

So… we now have a few possible paths in front of us:

### Be REALLY opinionated
We could just implement small things like #59 as the _default_. Forget about keeping `erl_prettypr` as the _canonical_ way of formatting and just define our own _canonical_ way (without adding an option to change that).
That would allow us to even remove some currently existing options, like `newline_after_attributes` and maybe improve their implementation a bit, now that we don't need to deal with both versions of it.
The downside of this approach is that anybody that doesn't like _our_ formatting style will have to implement their own formatter. It's kind of _My way or the highway_ and that's something we wanted to avoid since day 1 as well.

### Provide a different way to customize the formatter
Instead of keep adding option after option for the formatter, we could _squash_ multiple options into what we could call _themes_ or _styles_, in a way that could be similar to `elvis`' _rulesets_.
The idea here could be to provide a single option: `{style, module()}` and that module would implement a behavior (say `rebar3_formatter_style`). We could provide two of those modules with the plugin itself:
* `otp_style` representing what `erl_prettypr` does today.
* `default_style`, the default style, which would be what _we_ consider a sane default.
Then we should make sure that we allow devs to use their own modules there.
Or maybe we could accept contributions from the community for things like `comma_first_style` or others.

## RFC
This issue is a _Request for Comments_. The idea is to listen to what our users have to say and then decide on the best idea for this.

/cc @juanbono, @diegomanuel, @facundoolano

**Comment by facundoolano** [comment]
I agree in that 1. sticking too closely too erl_prettypr is not the most productive since it produces code that's likely to be undesirable by most people (for different reasons) and 2. being too opinionated will produce a formatter fit for us but not interesting to most other people.

If we want this to be helpful to us but also to the rest of the community we need to make it customizable one way or the other. Being erlang a mature language it's not realistic to expect a defacto standard format to arise and be widely adopted. Even the elixir formatter provides some degree of customization. The one important thing is that the default should be _sane_ (by some definition of it, that is, whatever we think should be less controversial for most people, e.g. no comma-first indentation :trollface: ).

I do think it can make sense to be strict about the amount of customization we want to allow to make the formatter maintainable. Maybe we can come up with some rules of thumb to determine when a given option is reasonable to request/implement and when not.

Regarding how to implement the customization (stand alone rules, behaviors with themes, etc.), I don't have strong opinions. Most formatters I used in other languages accept a style file in the repo so I sort of assumed that would be the way to define them, but whatever to extend should be fine.

A final note about erl_prettypr print and erlang-mode. As an erlang-mode user I perceive it to be far less opinionated than erl_prettypr. It mostly imposes how to indent a given line, but not how to insert line breaks and stuff like that. E.g. all of these are valid to erlang-mode:

```erl
try Test = 1,
     Test end,

try Test = 1,
     Test 
end,

try 
    Test = 1,
    Test 
end,
``` 

So I think a more reasonable default than sticking to erl_prettypr would be to respect it wherever it does the same as erlang-mode, and use some other criteria to make the rest of the choices.
