### ISSUE TITLE
Verify or ci mode

### ISSUE THREAD

**Issue by tommysanterre** [AdRoll/rebar3_format#92]
I want to make sure everyone runs the formatter but not run it for them to avoid diff in my pull requests unrelated to my changes.

Having a verify or ci mode that runs the formatter without formatting and returns a non-zero exit code if any files were not formatted would let me detect on my ci build if the formatter was properly run.

**Comment by elbrujohalcon** [comment]
That's a great idea!
We actually implemented a [poor-man solution](https://github.com/AdRoll/spillway/blob/master/.travis.yml#L17) on our projects because we didn't think about this 🤦‍♂ .

**Comment by tommysanterre** [comment]
I have no merit :) I stole the idea from another formatter.
https://github.com/vvakame/typescript-formatter

**Comment by dtip** [comment]
This was straightforward to add to steamroller with a binary match: https://github.com/old-reliable/steamroller/blob/master/src/steamroller_formatter.erl#L21-L28

It looks like you have the formatted code as a binary here: https://github.com/AdRoll/rebar3_format/blob/master/src/rebar3_formatter.erl#L90

I think if you add a `check` option, then read the original file & compare if this option is set, it should be easy enough to add this. There's a little extra complexity because I think you'll have to add some code to throw/catch the error.

Haven't read the code enough to implement this myself, but I hope it helps!

**Comment by tommysanterre** [comment]
Works on my project.

Thanks!

**Comment by tommysanterre** [comment]
Finally I have some files that don't pass the verify command but won't format
Here's one example.

```
-module(condom_gp_discovery_client_sup).

-behaviour(supervisor).

%% API

-export([start_link/0]).

%% Supervisor callbacks

-export([init/1]).

%%%===================================================================
%%% API functions
%%%===================================================================

start_link() ->
  supervisor:start_link({local, ?MODULE}, ?MODULE, []).

%%%===================================================================
%%% Supervisor callbacks
%%%===================================================================

init([]) ->
  {ok,
   {#{strategy => one_for_one, intensity => 5, period => 1},
    [#{id => condom_gp_ip_scan_sup,
       start => {condom_gp_ip_scan_sup, start_link, []},
       type => supervisor},
     #{id => condom_gp_broadcast_discovery_client,
       start => {condom_gp_broadcast_discovery_client, start_link, []},
       type => worker},
     #{id => condom_gp_discovery_client,
       start => {condom_gp_discovery_client, start_link, []},
       type => worker}]}}.

%%%===================================================================
%%% Internal functions
%%%===================================================================
```

**Comment by elbrujohalcon** [comment]
@tommysanterre you are correct. There is a bug.

**Comment by tommysanterre** [comment]
Thanks for the second fix!
